export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const HIDE_SEARCH_INPUT = 'HIDE_SEARCH_INPUT';
export const SHOW_SEARCH_INPUT = 'SHOW_SEARCH_INPUT';
export const OPEN_FAVOURITE = 'OPEN_FAVOURITE';
export const BACK_PRESSED = 'BACK_PRESSED';
export const SHOW_CRYPTO_DETAILS = 'SHOW_CRYPTO_DETAILS';

export const LOAD_COINS = 'LOAD_COINS';
export const RECEIVED_COINS = 'RECEIVED_COINS';
export const FAILURE_LOAD_COINS = 'FAILURE_LOAD_COINS';

export const LOAD_COIN = 'LOAD_COIN';
export const RECEIVED_COIN = 'RECEIVED_COIN';
export const FAILURE_LOAD_COIN = 'FAILURE_LOAD_COIN';

export const LOAD_FAVOURITE_COINS = 'LOAD_FAVOURITE_COINS';
export const RECEIVED_FAVOURITE_COINS = 'RECEIVED_FAVOURITE_COINS';
export const FAILURE_LOAD_FAVOURITE_COINS = 'FAILURE_LOAD_FAVOURITE_COINS';

