export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const HIDE_SEARCH_INPUT = 'HIDE_SEARCH_INPUT';
export const SHOW_SEARCH_INPUT = 'SHOW_SEARCH_INPUT';
export const OPEN_FAVOURITE = 'OPEN_FAVOURITE';
export const BACK_PRESSED = 'BACK_PRESSED';
